server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: baodaren123
  application:
    name: micro-product

  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
logging:
  level.com.example.product=debug


