server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: baodaren123
  application:
    name: micro-order
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

